version: "3.8"

services:
  backend:
    image: backend-fastapi:latest
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./fastapi:/usr/src/app
      # - /usr/src/app/data
    command: uvicorn api:app --host 0.0.0.0 --port 8080

  frontend:
    image: frontend-react:latest-dev
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
